name: tmdb_movie_app
description: A Flutter movie app using TMDB API.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.5
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.2
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.1.14
  intl: ^0.18.1
  path_provider: ^2.1.1
  pip_view: ^0.9.7
  video_thumbnail: ^0.5.3
  connectivity_plus: ^4.0.2
  dio: ^5.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true